### ISSUE TITLE
Open with menu option does not work for all file types

### ISSUE THREAD

**Issue by kasunch** [meganz/android#189] opened 2022-04-24 10:20 UTC
## General Information

- **MEGA Version:** 
6.7
- **OS Version(s):** 
Android 10
- **Devices/Simulators:** 
Samsung Galaxy S9 SM-G960F
- **Reproducible? (Yes/No):** 
Yes
##  What happened?
Some of the file types can be opened from external apps via the "Open with" menu option.
However, this functionality does not work for all the file types.

For example, I get a message saying "You many not have any apps installed which support this file type" when I open a `.kdbx` (KeePass Password Database) file via the "Open with" menu option.
However, I can use an external app to open files such as PDFs.

The issue has been discussed in [reddit](https://www.reddit.com/r/MEGA/comments/fuguy1/mega_android_app_how_to_openexecutepreview_a_file/) as well without leading to any flexible solution.

A temporary solution would be downloading the file in question first and open the downloaded file.
However, this is prone to use stale files if you forget to download every time. 

## What did you expect to happen?
MEGA app should provide a functionality to open files via external apps as needed.

**Comment by voc-mega** [comment] 2022-05-16 15:27
Hello,
Sorry for the delay on the response and thank you for reporting this.
We have been able to reproduce the issue you are reporting and it will be fixed in future releases.
We will contact you once it's fixed.
Thanks for the feedback and we will be in touch!

**Comment by kasunch** [comment] 2022-05-17 22:28
@voc-mega Thanks a lot for looking into this.

**Comment by javiergm1983** [comment] 2022-07-21 07:02
Hi @kasunch the fix for this issue has been applied into the MEGA Android v6.12, which is live since 2 weeks ago, so I will close this issue.

Please do not hesitate to reopen it if the issue persist. Thanks.

**Closed by javiergm1983** 2022-07-21 07:02 UTC
