### ISSUE TITLE
[Bug] Crash when choosing download loation

### ISSUE THREAD

**Issue by Thewisem** [meganz/android#133] opened 2021-02-19 00:53 UTC
## General Information
When I try to change the download location, it crashes every time.
- **MEGA Version:** 
- 4.0.0

- **OS Version(s):** 
- 7.0.0

- **Devices/Simulators:** 
- Samsung galaxt Tab A

- **Reproducible? (Yes/No):** 
- Yes

##  What happened?
... Crashes when there is external storage shown. When trying to xhange the location it crashes when reaching the internal or sd card storage section

## What did you expect to happen?
... Not crash I guess

**Comment by javiergm1983** [comment] 2021-02-19 08:25
Hi @Thewisem, thanks for reporting.
Please, can you provide the exact steps to reproduce the issue or give us the crash dump or stack trace?

**Comment by Thewisem** [comment] 2021-02-19 10:46
I tried to open SD card. I don't know how it was able to open internal storage. It used to crash but now it opened. I have a video to show but it seems I can't upload it. Send me your email so that I can send the video preview to you.

**Comment by Thewisem** [comment] 2021-02-19 10:49
Hope this helps. :)

**Comment by javiergm1983** [comment] 2021-02-19 12:40
Hi again, I have tried to reproduce your issue but it is not reproducible in any of my test devices with SD card support.

Did you checked that the SD card works fine?
Maybe it is damaged or write locked.

If the issue persist, please contact by email with our support department (support@mega.nz). They will provide you assistance to provide us logs to help debug the issue.
Please, also provide them this bug number in GitHub to our support team. Thanks.

**Comment by Thewisem** [comment] 2021-02-19 12:43
My SD card works fine. Thank you very much. OK I will try to contact them

**Comment by javiergm1983** [comment] 2021-03-03 09:51
Hi @Thewisem , we have received your logs via our support team and although we cannot reproduce the issue now can see the crash there.
Seems and specific crash that happens in your tablet device due your OS version.
Could you check if you have your device OS updated to the latest available version.

We will try to investigate the cause and try to fix as soon as possible.

**Comment by Thewisem** [comment] 2021-03-03 09:53
I am using an old tab. And as you know about how the android update works. I think you know what I mean. I cannot update my tab. :(

**Comment by javiergm1983** [comment] 2021-03-03 09:57
> I am using an old tab. And as you know about how the android update works. I think you know what I mean. I cannot update my tab. :(

Yes, it is what I supposed. It was just to be sure.

**Comment by Thewisem** [comment] 2021-03-03 09:59
Ok Thanks for the concern. Hope the issue is fixed soon

**Comment by javiergm1983** [comment] 2021-03-15 13:59
Hi @Thewisem, I am glad to imfor you that we are working on a fix to avoid this issue.
The fix is planned to be included in the future v4.1.1, so please when you receive that app update, please check that you problem has been solved and let us to know to proceed close this issue. Thanks.

**Comment by Thewisem** [comment] 2021-03-20 18:40
And I am glad to inform you that the issue has been fixed. Now it is working. Good Job. Kudos. :)

**Closed** 2021-03-22 09:32 UTC
